### ISSUE TITLE
Readme example not currently working

### ISSUE THREAD

**Issue by jefffriesen** [DatenMetzgerX/parallel.es#105]
I'm trying to get the basic example in the readme working. I've tried on node.js and in the browser. I thought this may be a regression so I tried both version 0.1.18 and 0.1.17 without getting correct results.

### Browser
Not using ParallelEsPlugin. I've tried the version of this function without the `.subscribe` as well with the same results.
```js
const parallel = require('parallel-es')
parallel
  .range(0, 10)
  .map(value => value * value)
  .subscribe((subresult, taskIndex) =>
    console.log(`The result of the task ${taskIndex} is`, subresult)
  )  
  .then(result => console.log(result))
```
error:
```
GET http://localhost:5000/worker-slave.parallel.js 404 (Not Found)
	t.exports	@	browser-commonjs.parallel.js:2
        value	@	browser-commonjs.parallel.js:1
```

### Node.js
node.js version 7.10, no webpack or transpilation. I've tried the version of this function without the `.subscribe` as well with the same results
```js
// You mentioned default on the require. I still had to use default for v0.1.18 to have parallel.range be found
const parallel = require('parallel-es').default  
parallel
  .range(0, 10)
  .map(value => value * value)
  .subscribe((subresult, taskIndex) =>
    console.log(`The result of the task ${taskIndex} is`, subresult)
  ) 
  .then(result => console.log(result))
```

result 
```
The result of the task 0 is [ null ]
The result of the task 8 is [ null ]
The result of the task 5 is [ null ]
The result of the task 9 is [ null ]
The result of the task 1 is [ null ]
The result of the task 4 is [ null ]
The result of the task 6 is [ null ]
The result of the task 7 is [ null ]
The result of the task 2 is [ null ]
The result of the task 3 is [ null ]
[ null, null, null, null, null, null, null, null, null, null ]
```

**Comment by MichaReiser** [comment]
For the browser: If you are not using the webpack plugin you have to copy the worker-slave.parallel.js to the target directory (or copying it with the webpack copy files plugin). 

For nodejs: 
Default needs to be used as parallel use ES6 modules but nodejs uses commonjs. So either use Babel or TypeScript to transpile your Source Code to ES5 or use the `.default`.

The result for node.js seems to be correct?

**Comment by jefffriesen** [comment]
Ok, I'll try that suggestion for the browser. 

For the result in the node.js example, its mapping 'value * value' over a range. I would assume when the range hit 5, for example, it would be 25, not null. So the result would be:
[0, 1, 4, 9, 16, 25, ...]

I'm just using your example from the readme.

**Comment by MichaReiser** [comment]
> For the result in the node.js example, its mapping 'value * value' over a range. I would assume when the range hit 5, for example, it would be 25, not null. So the result would be:
[0, 1, 4, 9, 16, 25, ...]

But your function is not returning any value... so you're mapping all values to undefined

**Comment by MichaReiser** [comment]
> For the result in the node.js example, its mapping 'value * value' over a range. I would assume when the range hit 5, for example, it would be 25, not null. So the result would be:
[0, 1, 4, 9, 16, 25, ...]

This is most certainly because you use a lambda expression (and no source transpilation). Try to use a normal JS function for the map operation.

The function serializer currently lacks the knowledge if a function is a lambda function or not. I fear that this information is not available and, therefore, needs to be determined by parsing the function's source code.

**Comment by jefffriesen** [comment]
Ok, things are starting to make more sense. When I read your first comment I was doubtful that was it because I was using the latest version of node.js, which works fine with lamda functions. So I did this test:

```js
const range = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
const sequentialValues = range.map(value => value * value)
console.log('sequential values: ', sequentialValues)

// converted lamdas to es5 functions
parallel
  .range(0, 10)
  .map(function(value) {
    return value * value
  })
  .subscribe(function(subresult, taskIndex) {
    console.log(`The result of the task ${taskIndex} is`, subresult)
  })
  .then(function(result) {
    console.log('parallel values: ', result)
  })
```

With these results:
```js
sequential values:  [ 0, 1, 4, 9, 16, 25, 36, 49, 64, 81 ]
The result of the task 0 is [ 0 ]
The result of the task 8 is [ 64 ]
The result of the task 9 is [ 81 ]
The result of the task 7 is [ 49 ]
The result of the task 4 is [ 16 ]
The result of the task 6 is [ 36 ]
The result of the task 2 is [ 4 ]
The result of the task 1 is [ 1 ]
The result of the task 5 is [ 25 ]
The result of the task 3 is [ 9 ]
parallel values:  [ 0, 1, 4, 9, 16, 25, 36, 49, 64, 81 ]
```

I've now read your edited comment and it makes a lot more sense. Thank you. 

I'm hoping to contribute some documentation PRs or an example repo. I would love this library to get more traction and I think some more examples will help.

**Comment by MichaReiser** [comment]
I would love to see that. There is an [example repo](https://github.com/MichaReiser/parallel-es-example) but just for the browser use case (that uses babel).

I also hope that I will have time in the near future to extend the Node support.
